In [2]:
import numpy as np


In [3]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


In [13]:
# 1. How many negative numbers are there?
a[a <0]

array([-2, -1, -6, -7])

In [14]:
# 2. How many positive numbers are there?
a[a > 0]

array([ 4, 10, 12, 23,  3])

In [16]:
# 3. How many even positive numbers are there?
a[(a > 0) & (a % 2 == 0)]

array([ 4, 10, 12])

In [22]:
# 4. If you were to add 3 to each data point, how many positive numbers would there be?
a_1 = a + 1
a_1[(a_1 > 0) & (a_1 % 2 == 0)]

array([24,  4])

In [23]:
# 5. If you squared each number, what would the new mean and standard deviation be?
a_squared = a ** 2

In [25]:
a_squared.std()

144.0243035046516

In [26]:
a_squared.mean()

74.0

In [31]:
# 6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.
a_center = a / a.mean()
a_center

array([ 1.33333333,  3.33333333,  4.        ,  7.66666667, -0.66666667,
       -0.33333333,  0.        ,  0.        ,  0.        , -2.        ,
        1.        , -2.33333333])

In [42]:
# 7. Calculate the z-score for each data point.
a_zscore = ((-a.mean()) / (a.std())) * a
a_zscore

array([-1.48841682, -3.72104204, -4.46525045, -8.55839669,  0.74420841,
        0.3721042 , -0.        , -0.        , -0.        ,  2.23262522,
       -1.11631261,  2.60472943])

In [43]:
# more numpy exercises
## setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [45]:
# 1. Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = sum(a)

In [46]:
sum_of_a

55

In [47]:
# 2. Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = min(a)

In [48]:
min_of_a

1

In [49]:
# 3. Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = max(a)

In [50]:
max_of_a

10

In [52]:
# 4. Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = sum_of_a / len(a)

In [53]:
mean_of_a

5.5

In [54]:
# 5. Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
def prod_list(my_list):
    result = 1
    for x in my_list:
        result = result * x
    return result

In [55]:
prod_list(a)

3628800

In [56]:
product_of_a = prod_list(a)

In [57]:
product_of_a

3628800